/**
 * Naming-practice questions.
 *
 * Generated by scripts/build-quiz-bank.mjs — do not edit by hand. Every entry
 * has been round-tripped: PubChem supplied the name, and OPSIN read that name
 * back to the structure it is paired with here.
 */

export interface BankQuestion {
  category: string;
  smiles: string;
  /** The IUPAC name, verified against the structure. */
  name: string;
  /** PubChem's common title, used for the "also known as" line. */
  title: string;
  difficulty: "easy" | "medium" | "hard";
}

export const QUIZ_BANK: BankQuestion[] = [
  {
    "category": "acids",
    "smiles": "CC(Cl)C(=O)O",
    "name": "2-chloropropanoic acid",
    "title": "2-Chloropropionic acid",
    "difficulty": "medium"
  },
  {
    "category": "acids",
    "smiles": "CC(C(=O)O)CC",
    "name": "2-methylbutanoic acid",
    "title": "2-Methylbutanoic Acid",
    "difficulty": "medium"
  },
  {
    "category": "acids",
    "smiles": "CC(C)C(=O)O",
    "name": "2-methylpropanoic acid",
    "title": "Isobutyric Acid",
    "difficulty": "easy"
  },
  {
    "category": "acids",
    "smiles": "CC(C)C(C)C(=O)O",
    "name": "2,3-dimethylbutanoic acid",
    "title": "2,3-Dimethylbutanoic acid",
    "difficulty": "hard"
  },
  {
    "category": "acids",
    "smiles": "OC(=O)C(C)CC(C)C",
    "name": "2,4-dimethylpentanoic acid",
    "title": "2,4-Dimethylpentanoic acid",
    "difficulty": "hard"
  },
  {
    "category": "acids",
    "smiles": "CC(C)CC(=O)O",
    "name": "3-methylbutanoic acid",
    "title": "Isovaleric Acid",
    "difficulty": "easy"
  },
  {
    "category": "acids",
    "smiles": "CC(=O)N",
    "name": "acetamide",
    "title": "Acetamide",
    "difficulty": "easy"
  },
  {
    "category": "acids",
    "smiles": "CC(=O)O",
    "name": "acetic acid",
    "title": "Acetic Acid",
    "difficulty": "easy"
  },
  {
    "category": "acids",
    "smiles": "CC(=O)Cl",
    "name": "acetyl chloride",
    "title": "Acetyl chloride",
    "difficulty": "easy"
  },
  {
    "category": "acids",
    "smiles": "OC(=O)CCC(=O)O",
    "name": "butanedioic acid",
    "title": "Succinic Acid",
    "difficulty": "medium"
  },
  {
    "category": "acids",
    "smiles": "CCCC(=O)O",
    "name": "butanoic acid",
    "title": "Butyric Acid",
    "difficulty": "easy"
  },
  {
    "category": "acids",
    "smiles": "CCC(C)C(=O)OCC",
    "name": "ethyl 2-methylbutanoate",
    "title": "Ethyl 2-methylbutyrate",
    "difficulty": "hard"
  },
  {
    "category": "acids",
    "smiles": "CC(=O)OCC",
    "name": "ethyl acetate",
    "title": "Ethyl Acetate",
    "difficulty": "easy"
  },
  {
    "category": "acids",
    "smiles": "CCCC(=O)OCC",
    "name": "ethyl butanoate",
    "title": "Ethyl butyrate",
    "difficulty": "medium"
  },
  {
    "category": "acids",
    "smiles": "C(=O)OCC",
    "name": "ethyl formate",
    "title": "Ethyl formate",
    "difficulty": "easy"
  },
  {
    "category": "acids",
    "smiles": "CCC(=O)OCC",
    "name": "ethyl propanoate",
    "title": "Ethyl Propionate",
    "difficulty": "easy"
  },
  {
    "category": "acids",
    "smiles": "CCCCCCC(=O)O",
    "name": "heptanoic acid",
    "title": "Heptanoic Acid",
    "difficulty": "easy"
  },
  {
    "category": "acids",
    "smiles": "CCCCCC(=O)O",
    "name": "hexanoic acid",
    "title": "Hexanoic Acid",
    "difficulty": "easy"
  },
  {
    "category": "acids",
    "smiles": "CC(C)C(C)C(=O)OC",
    "name": "methyl 2,3-dimethylbutanoate",
    "title": "2,3-Dimethyl-butanoic acid methyl ester",
    "difficulty": "hard"
  },
  {
    "category": "acids",
    "smiles": "CC(=O)OC",
    "name": "methyl acetate",
    "title": "Methyl Acetate",
    "difficulty": "easy"
  },
  {
    "category": "acids",
    "smiles": "CCCC(=O)OC",
    "name": "methyl butanoate",
    "title": "Methyl butyrate",
    "difficulty": "easy"
  },
  {
    "category": "acids",
    "smiles": "C(=O)OC",
    "name": "methyl formate",
    "title": "Methyl formate",
    "difficulty": "easy"
  },
  {
    "category": "acids",
    "smiles": "CCC(=O)OC",
    "name": "methyl propanoate",
    "title": "Methyl propionate",
    "difficulty": "easy"
  },
  {
    "category": "acids",
    "smiles": "CC(=O)NC",
    "name": "N-methylacetamide",
    "title": "N-Methylacetamide",
    "difficulty": "easy"
  },
  {
    "category": "acids",
    "smiles": "OC(=O)CCCC(=O)O",
    "name": "pentanedioic acid",
    "title": "Glutaric Acid",
    "difficulty": "medium"
  },
  {
    "category": "acids",
    "smiles": "CCCCC(=O)O",
    "name": "pentanoic acid",
    "title": "Pentanoic Acid",
    "difficulty": "easy"
  },
  {
    "category": "acids",
    "smiles": "CC(C)CC(=O)OC(C)C",
    "name": "propan-2-yl 3-methylbutanoate",
    "title": "Isopropyl isovalerate",
    "difficulty": "hard"
  },
  {
    "category": "acids",
    "smiles": "CCC(=O)N",
    "name": "propanamide",
    "title": "Propionamide",
    "difficulty": "easy"
  },
  {
    "category": "acids",
    "smiles": "OC(=O)CC(=O)O",
    "name": "propanedioic acid",
    "title": "Malonic Acid",
    "difficulty": "easy"
  },
  {
    "category": "acids",
    "smiles": "CCC(=O)O",
    "name": "propanoic acid",
    "title": "Propionic Acid",
    "difficulty": "easy"
  },
  {
    "category": "acids",
    "smiles": "CCC(=O)Cl",
    "name": "propanoyl chloride",
    "title": "Propionyl chloride",
    "difficulty": "easy"
  },
  {
    "category": "acids",
    "smiles": "CC(=O)OCCC",
    "name": "propyl acetate",
    "title": "Propyl Acetate",
    "difficulty": "easy"
  },
  {
    "category": "acids",
    "smiles": "CCCC(=O)OCCC",
    "name": "propyl butanoate",
    "title": "Propyl butyrate",
    "difficulty": "medium"
  },
  {
    "category": "acids",
    "smiles": "C(=O)OCCC",
    "name": "propyl formate",
    "title": "Propyl formate",
    "difficulty": "easy"
  },
  {
    "category": "acids",
    "smiles": "CCC(=O)OCCC",
    "name": "propyl propanoate",
    "title": "Propyl propionate",
    "difficulty": "medium"
  },
  {
    "category": "alcohols",
    "smiles": "CCCOC",
    "name": "1-methoxypropane",
    "title": "Methyl propyl ether",
    "difficulty": "easy"
  },
  {
    "category": "alcohols",
    "smiles": "CCOC(C)(C)C",
    "name": "2-ethoxy-2-methylpropane",
    "title": "Ethyl tert-butyl ether",
    "difficulty": "easy"
  },
  {
    "category": "alcohols",
    "smiles": "COC(C)C",
    "name": "2-methoxypropane",
    "title": "2-Methoxypropane",
    "difficulty": "easy"
  },
  {
    "category": "alcohols",
    "smiles": "OCC(C)CC",
    "name": "2-methylbutan-1-ol",
    "title": "2-Methyl-1-butanol",
    "difficulty": "hard"
  },
  {
    "category": "alcohols",
    "smiles": "CC1CCCCC1O",
    "name": "2-methylcyclohexan-1-ol",
    "title": "2-Methylcyclohexanol",
    "difficulty": "hard"
  },
  {
    "category": "alcohols",
    "smiles": "CC(C)CO",
    "name": "2-methylpropan-1-ol",
    "title": "Isobutanol",
    "difficulty": "medium"
  },
  {
    "category": "alcohols",
    "smiles": "CC(C)(C)O",
    "name": "2-methylpropan-2-ol",
    "title": "tert-Butanol",
    "difficulty": "easy"
  },
  {
    "category": "alcohols",
    "smiles": "OCC(C)C(C)CC",
    "name": "2,3-dimethylpentan-1-ol",
    "title": "2,3-Dimethyl-1-pentanol",
    "difficulty": "hard"
  },
  {
    "category": "alcohols",
    "smiles": "CC(C)C(O)C(C)C",
    "name": "2,4-dimethylpentan-3-ol",
    "title": "2,4-Dimethyl-3-pentanol",
    "difficulty": "hard"
  },
  {
    "category": "alcohols",
    "smiles": "OC1CC(C)CCC1",
    "name": "3-methylcyclohexan-1-ol",
    "title": "3-Methylcyclohexanol",
    "difficulty": "hard"
  },
  {
    "category": "alcohols",
    "smiles": "CC(C)CC(O)CC",
    "name": "5-methylhexan-3-ol",
    "title": "3-Hexanol, 5-methyl-",
    "difficulty": "hard"
  },
  {
    "category": "alcohols",
    "smiles": "C(O)CCC",
    "name": "butan-1-ol",
    "title": "1-Butanol",
    "difficulty": "easy"
  },
  {
    "category": "alcohols",
    "smiles": "CC(O)CC",
    "name": "butan-2-ol",
    "title": "(+-)-2-Butanol",
    "difficulty": "medium"
  },
  {
    "category": "alcohols",
    "smiles": "OC1CCCCC1",
    "name": "cyclohexanol",
    "title": "Cyclohexanol",
    "difficulty": "easy"
  },
  {
    "category": "alcohols",
    "smiles": "OCCO",
    "name": "ethane-1,2-diol",
    "title": "Ethylene Glycol",
    "difficulty": "medium"
  },
  {
    "category": "alcohols",
    "smiles": "CCOCC",
    "name": "ethoxyethane",
    "title": "Diethyl Ether",
    "difficulty": "easy"
  },
  {
    "category": "alcohols",
    "smiles": "C(O)CCCCCC",
    "name": "heptan-1-ol",
    "title": "Heptanol",
    "difficulty": "easy"
  },
  {
    "category": "alcohols",
    "smiles": "CC(O)CCCCC",
    "name": "heptan-2-ol",
    "title": "2-Heptanol",
    "difficulty": "medium"
  },
  {
    "category": "alcohols",
    "smiles": "CCC(O)CCCC",
    "name": "heptan-3-ol",
    "title": "3-Heptanol",
    "difficulty": "medium"
  },
  {
    "category": "alcohols",
    "smiles": "CCCC(O)CCC",
    "name": "heptan-4-ol",
    "title": "4-Heptanol",
    "difficulty": "easy"
  },
  {
    "category": "alcohols",
    "smiles": "C(O)CCCCC",
    "name": "hexan-1-ol",
    "title": "1-Hexanol",
    "difficulty": "easy"
  },
  {
    "category": "alcohols",
    "smiles": "CC(O)CCCC",
    "name": "hexan-2-ol",
    "title": "2-Hexanol",
    "difficulty": "medium"
  },
  {
    "category": "alcohols",
    "smiles": "CCC(O)CCC",
    "name": "hexan-3-ol",
    "title": "3-Hexanol",
    "difficulty": "medium"
  },
  {
    "category": "alcohols",
    "smiles": "COCC",
    "name": "methoxyethane",
    "title": "Methoxyethane",
    "difficulty": "easy"
  },
  {
    "category": "alcohols",
    "smiles": "COC",
    "name": "methoxymethane",
    "title": "Dimethyl Ether",
    "difficulty": "easy"
  },
  {
    "category": "alcohols",
    "smiles": "C(O)CCCC",
    "name": "pentan-1-ol",
    "title": "1-Pentanol",
    "difficulty": "easy"
  },
  {
    "category": "alcohols",
    "smiles": "CC(O)CCC",
    "name": "pentan-2-ol",
    "title": "2-Pentanol",
    "difficulty": "medium"
  },
  {
    "category": "alcohols",
    "smiles": "CCC(O)CC",
    "name": "pentan-3-ol",
    "title": "3-Pentanol",
    "difficulty": "easy"
  },
  {
    "category": "alcohols",
    "smiles": "C(O)CC",
    "name": "propan-1-ol",
    "title": "1-Propanol",
    "difficulty": "easy"
  },
  {
    "category": "alcohols",
    "smiles": "CC(O)C",
    "name": "propan-2-ol",
    "title": "Isopropanol",
    "difficulty": "easy"
  },
  {
    "category": "alcohols",
    "smiles": "CC(O)CO",
    "name": "propane-1,2-diol",
    "title": "Propylene Glycol",
    "difficulty": "hard"
  },
  {
    "category": "alcohols",
    "smiles": "OCC(O)CO",
    "name": "propane-1,2,3-triol",
    "title": "Glycerol",
    "difficulty": "medium"
  },
  {
    "category": "alcohols",
    "smiles": "OCCCO",
    "name": "propane-1,3-diol",
    "title": "1,3-Propanediol",
    "difficulty": "medium"
  },
  {
    "category": "alkanes",
    "smiles": "CC1CCCCC1C",
    "name": "1,2-dimethylcyclohexane",
    "title": "1,2-Dimethylcyclohexane",
    "difficulty": "hard"
  },
  {
    "category": "alkanes",
    "smiles": "CC1CCCC(C)C1",
    "name": "1,3-dimethylcyclohexane",
    "title": "1,3-Dimethylcyclohexane",
    "difficulty": "hard"
  },
  {
    "category": "alkanes",
    "smiles": "CC1CCC(C)CC1",
    "name": "1,4-dimethylcyclohexane",
    "title": "1,4-Dimethylcyclohexane",
    "difficulty": "hard"
  },
  {
    "category": "alkanes",
    "smiles": "CC(C)CCCCC",
    "name": "2-methylheptane",
    "title": "2-Methylheptane",
    "difficulty": "medium"
  },
  {
    "category": "alkanes",
    "smiles": "CC(C)CCCC",
    "name": "2-methylhexane",
    "title": "2-Methylhexane",
    "difficulty": "easy"
  },
  {
    "category": "alkanes",
    "smiles": "CC(C)CCCCCC",
    "name": "2-methyloctane",
    "title": "2-Methyloctane",
    "difficulty": "medium"
  },
  {
    "category": "alkanes",
    "smiles": "CC(C)CCC",
    "name": "2-methylpentane",
    "title": "2-Methylpentane",
    "difficulty": "easy"
  },
  {
    "category": "alkanes",
    "smiles": "CC(C)(C)CCCCC",
    "name": "2,2-dimethylheptane",
    "title": "2,2-Dimethylheptane",
    "difficulty": "medium"
  },
  {
    "category": "alkanes",
    "smiles": "CC(C)(C)CCCC",
    "name": "2,2-dimethylhexane",
    "title": "2,2-Dimethylhexane",
    "difficulty": "medium"
  },
  {
    "category": "alkanes",
    "smiles": "CC(C)(C)CCC",
    "name": "2,2-dimethylpentane",
    "title": "2,2-Dimethylpentane",
    "difficulty": "medium"
  },
  {
    "category": "alkanes",
    "smiles": "CC(C)C(C)CCCC",
    "name": "2,3-dimethylheptane",
    "title": "2,3-Dimethylheptane",
    "difficulty": "hard"
  },
  {
    "category": "alkanes",
    "smiles": "CC(C)C(C)CCC",
    "name": "2,3-dimethylhexane",
    "title": "2,3-Dimethylhexane",
    "difficulty": "hard"
  },
  {
    "category": "alkanes",
    "smiles": "CC(C)C(C)CC",
    "name": "2,3-dimethylpentane",
    "title": "2,3-Dimethylpentane",
    "difficulty": "hard"
  },
  {
    "category": "alkanes",
    "smiles": "CC(C)C(C)C(C)C",
    "name": "2,3,4-trimethylpentane",
    "title": "2,3,4-Trimethylpentane",
    "difficulty": "hard"
  },
  {
    "category": "alkanes",
    "smiles": "CC(C)CC(C)CCC",
    "name": "2,4-dimethylheptane",
    "title": "2,4-Dimethylheptane",
    "difficulty": "hard"
  },
  {
    "category": "alkanes",
    "smiles": "CC(C)CC(C)CC",
    "name": "2,4-dimethylhexane",
    "title": "2,4-Dimethylhexane",
    "difficulty": "hard"
  },
  {
    "category": "alkanes",
    "smiles": "CC(C)CC(C)C",
    "name": "2,4-dimethylpentane",
    "title": "2,4-Dimethylpentane",
    "difficulty": "hard"
  },
  {
    "category": "alkanes",
    "smiles": "CC(C)CCC(C)CC",
    "name": "2,5-dimethylheptane",
    "title": "2,5-Dimethylheptane",
    "difficulty": "hard"
  },
  {
    "category": "alkanes",
    "smiles": "CC(C)CCC(C)C",
    "name": "2,5-dimethylhexane",
    "title": "2,5-Dimethylhexane",
    "difficulty": "hard"
  },
  {
    "category": "alkanes",
    "smiles": "CC(C)CCCC(C)C",
    "name": "2,6-dimethylheptane",
    "title": "2,6-Dimethylheptane",
    "difficulty": "hard"
  },
  {
    "category": "alkanes",
    "smiles": "CCC(CC)C(C)CC",
    "name": "3-ethyl-4-methylhexane",
    "title": "3-Ethyl-4-methylhexane",
    "difficulty": "hard"
  },
  {
    "category": "alkanes",
    "smiles": "CCC(CC)CCCC",
    "name": "3-ethylheptane",
    "title": "3-Ethylheptane",
    "difficulty": "medium"
  },
  {
    "category": "alkanes",
    "smiles": "CCC(CC)CCC",
    "name": "3-ethylhexane",
    "title": "3-Ethylhexane",
    "difficulty": "medium"
  },
  {
    "category": "alkanes",
    "smiles": "CCC(CC)CCCCC",
    "name": "3-ethyloctane",
    "title": "3-Ethyloctane",
    "difficulty": "medium"
  },
  {
    "category": "alkanes",
    "smiles": "CCC(CC)CC",
    "name": "3-ethylpentane",
    "title": "3-Ethylpentane",
    "difficulty": "easy"
  },
  {
    "category": "alkanes",
    "smiles": "CC(CC)CCCC",
    "name": "3-methylheptane",
    "title": "3-Methylheptane",
    "difficulty": "hard"
  },
  {
    "category": "alkanes",
    "smiles": "CC(CC)CCC",
    "name": "3-methylhexane",
    "title": "3-Methylhexane",
    "difficulty": "medium"
  },
  {
    "category": "alkanes",
    "smiles": "CC(CC)CCCCCC",
    "name": "3-methylnonane",
    "title": "3-Methylnonane",
    "difficulty": "hard"
  },
  {
    "category": "alkanes",
    "smiles": "CC(CC)CCCCC",
    "name": "3-methyloctane",
    "title": "3-Methyloctane",
    "difficulty": "hard"
  },
  {
    "category": "alkanes",
    "smiles": "CCC(C)CC",
    "name": "3-methylpentane",
    "title": "3-Methylpentane",
    "difficulty": "easy"
  },
  {
    "category": "alkanes",
    "smiles": "CCC(C)(C)CCCC",
    "name": "3,3-dimethylheptane",
    "title": "3,3-Dimethylheptane",
    "difficulty": "medium"
  },
  {
    "category": "alkanes",
    "smiles": "CCC(C)(C)CCC",
    "name": "3,3-dimethylhexane",
    "title": "3,3-Dimethylhexane",
    "difficulty": "medium"
  },
  {
    "category": "alkanes",
    "smiles": "CCC(C)(C)CC",
    "name": "3,3-dimethylpentane",
    "title": "3,3-Dimethylpentane",
    "difficulty": "medium"
  },
  {
    "category": "alkanes",
    "smiles": "CCC(C)C(C)CCC",
    "name": "3,4-dimethylheptane",
    "title": "3,4-Dimethylheptane",
    "difficulty": "hard"
  },
  {
    "category": "alkanes",
    "smiles": "CCC(C)C(C)CC",
    "name": "3,4-dimethylhexane",
    "title": "3,4-Dimethylhexane",
    "difficulty": "hard"
  },
  {
    "category": "alkanes",
    "smiles": "CCC(C)CC(C)CC",
    "name": "3,5-dimethylheptane",
    "title": "3,5-Dimethylheptane",
    "difficulty": "hard"
  },
  {
    "category": "alkanes",
    "smiles": "CCCC(CC)CCC",
    "name": "4-ethylheptane",
    "title": "Heptane, 4-ethyl-",
    "difficulty": "medium"
  },
  {
    "category": "alkanes",
    "smiles": "CCCC(CC)CCCC",
    "name": "4-ethyloctane",
    "title": "4-Ethyloctane",
    "difficulty": "hard"
  },
  {
    "category": "alkanes",
    "smiles": "CCCC(C)CCC",
    "name": "4-methylheptane",
    "title": "4-Methylheptane",
    "difficulty": "medium"
  },
  {
    "category": "alkanes",
    "smiles": "CCCC(C)CCCC",
    "name": "4-methyloctane",
    "title": "4-Methyloctane",
    "difficulty": "hard"
  },
  {
    "category": "alkanes",
    "smiles": "CCCC(C)(C)CCC",
    "name": "4,4-dimethylheptane",
    "title": "4,4-Dimethylheptane",
    "difficulty": "medium"
  },
  {
    "category": "alkanes",
    "smiles": "CCCC",
    "name": "butane",
    "title": "Butane",
    "difficulty": "easy"
  },
  {
    "category": "alkanes",
    "smiles": "C1CCC1",
    "name": "cyclobutane",
    "title": "Cyclobutane",
    "difficulty": "easy"
  },
  {
    "category": "alkanes",
    "smiles": "C1CCCCCC1",
    "name": "cycloheptane",
    "title": "Cycloheptane",
    "difficulty": "easy"
  },
  {
    "category": "alkanes",
    "smiles": "C1CCCCC1",
    "name": "cyclohexane",
    "title": "Cyclohexane",
    "difficulty": "easy"
  },
  {
    "category": "alkanes",
    "smiles": "C1CCCC1",
    "name": "cyclopentane",
    "title": "Cyclopentane",
    "difficulty": "easy"
  },
  {
    "category": "alkanes",
    "smiles": "CCC1CCCCC1",
    "name": "ethylcyclohexane",
    "title": "Ethylcyclohexane",
    "difficulty": "medium"
  },
  {
    "category": "alkanes",
    "smiles": "CCCCCCC",
    "name": "heptane",
    "title": "Heptane",
    "difficulty": "easy"
  },
  {
    "category": "alkanes",
    "smiles": "CCCCCC",
    "name": "hexane",
    "title": "Hexane",
    "difficulty": "easy"
  },
  {
    "category": "alkanes",
    "smiles": "CC1CCCCC1",
    "name": "methylcyclohexane",
    "title": "Methylcyclohexane",
    "difficulty": "easy"
  },
  {
    "category": "alkanes",
    "smiles": "CCCCCCCC",
    "name": "octane",
    "title": "Octane",
    "difficulty": "easy"
  },
  {
    "category": "alkanes",
    "smiles": "CCCCC",
    "name": "pentane",
    "title": "Pentane",
    "difficulty": "easy"
  },
  {
    "category": "amines",
    "smiles": "CC[N+](=O)[O-]",
    "name": "1-nitroethane",
    "title": "Nitroethane",
    "difficulty": "easy"
  },
  {
    "category": "amines",
    "smiles": "NCC(C)CC(C)N",
    "name": "2-methylpentane-1,4-diamine",
    "title": "(racemic+meso) 2-Methyl-pentane-1,4-diamine",
    "difficulty": "hard"
  },
  {
    "category": "amines",
    "smiles": "CC(C)C#N",
    "name": "2-methylpropanenitrile",
    "title": "Isobutyronitrile",
    "difficulty": "medium"
  },
  {
    "category": "amines",
    "smiles": "CC(C)C(C)C#N",
    "name": "2,3-dimethylbutanenitrile",
    "title": "2,3-Dimethylbutanenitrile",
    "difficulty": "hard"
  },
  {
    "category": "amines",
    "smiles": "CC(C)CC(C)CN",
    "name": "2,4-dimethylpentan-1-amine",
    "title": "2,4-Dimethylpentan-1-amine",
    "difficulty": "hard"
  },
  {
    "category": "amines",
    "smiles": "CC(C)CC(C)C#N",
    "name": "2,4-dimethylpentanenitrile",
    "title": "2,4-Dimethylpentanenitrile",
    "difficulty": "hard"
  },
  {
    "category": "amines",
    "smiles": "CCC(C)C(C)N",
    "name": "3-methylpentan-2-amine",
    "title": "3-Methyl-2-pentanamine",
    "difficulty": "hard"
  },
  {
    "category": "amines",
    "smiles": "CC#N",
    "name": "acetonitrile",
    "title": "Acetonitrile",
    "difficulty": "easy"
  },
  {
    "category": "amines",
    "smiles": "CCCCN",
    "name": "butan-1-amine",
    "title": "Butylamine",
    "difficulty": "easy"
  },
  {
    "category": "amines",
    "smiles": "CCC(N)C",
    "name": "butan-2-amine",
    "title": "Sec-Butylamine",
    "difficulty": "medium"
  },
  {
    "category": "amines",
    "smiles": "CCCC#N",
    "name": "butanenitrile",
    "title": "Butyronitrile",
    "difficulty": "easy"
  },
  {
    "category": "amines",
    "smiles": "CCN",
    "name": "ethanamine",
    "title": "Ethylamine",
    "difficulty": "easy"
  },
  {
    "category": "amines",
    "smiles": "NCCN",
    "name": "ethane-1,2-diamine",
    "title": "Ethylenediamine",
    "difficulty": "medium"
  },
  {
    "category": "amines",
    "smiles": "CN",
    "name": "methanamine",
    "title": "Methylamine",
    "difficulty": "easy"
  },
  {
    "category": "amines",
    "smiles": "CCNCC",
    "name": "N-ethylethanamine",
    "title": "Diethylamine",
    "difficulty": "easy"
  },
  {
    "category": "amines",
    "smiles": "CNC",
    "name": "N-methylmethanamine",
    "title": "Dimethylamine",
    "difficulty": "easy"
  },
  {
    "category": "amines",
    "smiles": "CN(C)C",
    "name": "N,N-dimethylmethanamine",
    "title": "Trimethylamine",
    "difficulty": "easy"
  },
  {
    "category": "amines",
    "smiles": "CN(C)CC(C)C",
    "name": "N,N,2-trimethylpropan-1-amine",
    "title": "N,N-Dimethylisobutylamine",
    "difficulty": "medium"
  },
  {
    "category": "amines",
    "smiles": "C[N+](=O)[O-]",
    "name": "nitromethane",
    "title": "Nitromethane",
    "difficulty": "easy"
  },
  {
    "category": "amines",
    "smiles": "CCCCCN",
    "name": "pentan-1-amine",
    "title": "Pentylamine",
    "difficulty": "easy"
  },
  {
    "category": "amines",
    "smiles": "CCCCC#N",
    "name": "pentanenitrile",
    "title": "Valeronitrile",
    "difficulty": "easy"
  },
  {
    "category": "amines",
    "smiles": "CCCN",
    "name": "propan-1-amine",
    "title": "Propylamine",
    "difficulty": "easy"
  },
  {
    "category": "amines",
    "smiles": "CC(N)C",
    "name": "propan-2-amine",
    "title": "Isopropylamine",
    "difficulty": "easy"
  },
  {
    "category": "amines",
    "smiles": "NCCCN",
    "name": "propane-1,3-diamine",
    "title": "1,3-Propanediamine",
    "difficulty": "medium"
  },
  {
    "category": "amines",
    "smiles": "CCC#N",
    "name": "propanenitrile",
    "title": "Propionitrile",
    "difficulty": "easy"
  },
  {
    "category": "aromatics",
    "smiles": "Cc1ccc(cc1)[N+](=O)[O-]",
    "name": "1-methyl-4-nitrobenzene",
    "title": "4-Nitrotoluene",
    "difficulty": "medium"
  },
  {
    "category": "aromatics",
    "smiles": "Cc1ccc(cc1)C(C)C",
    "name": "1-methyl-4-propan-2-ylbenzene",
    "title": "P-Cymene",
    "difficulty": "hard"
  },
  {
    "category": "aromatics",
    "smiles": "Cc1ccccc1C",
    "name": "1,2-xylene",
    "title": "O-Xylene",
    "difficulty": "hard"
  },
  {
    "category": "aromatics",
    "smiles": "Clc1cccc(Cl)c1",
    "name": "1,3-dichlorobenzene",
    "title": "1,3-Dichlorobenzene",
    "difficulty": "medium"
  },
  {
    "category": "aromatics",
    "smiles": "Cc1cccc(C)c1",
    "name": "1,3-xylene",
    "title": "M-Xylene",
    "difficulty": "hard"
  },
  {
    "category": "aromatics",
    "smiles": "Cc1cc(C)cc(C)c1",
    "name": "1,3,5-trimethylbenzene",
    "title": "Mesitylene",
    "difficulty": "hard"
  },
  {
    "category": "aromatics",
    "smiles": "Clc1ccc(Cl)cc1",
    "name": "1,4-dichlorobenzene",
    "title": "1,4-Dichlorobenzene",
    "difficulty": "medium"
  },
  {
    "category": "aromatics",
    "smiles": "Cc1ccc(C)cc1",
    "name": "1,4-xylene",
    "title": "P-Xylene",
    "difficulty": "hard"
  },
  {
    "category": "aromatics",
    "smiles": "Nc1ccc(Cl)cc1",
    "name": "4-chloroaniline",
    "title": "4-Chloroaniline",
    "difficulty": "easy"
  },
  {
    "category": "aromatics",
    "smiles": "OC(=O)c1ccc(Cl)cc1",
    "name": "4-chlorobenzoic acid",
    "title": "4-Chlorobenzoic Acid",
    "difficulty": "medium"
  },
  {
    "category": "aromatics",
    "smiles": "Cc1ccc(C=O)cc1",
    "name": "4-methylbenzaldehyde",
    "title": "4-Methylbenzaldehyde",
    "difficulty": "medium"
  },
  {
    "category": "aromatics",
    "smiles": "OC(=O)c1ccc(C)cc1",
    "name": "4-methylbenzoic acid",
    "title": "P-Toluic Acid",
    "difficulty": "medium"
  },
  {
    "category": "aromatics",
    "smiles": "Oc1ccc(C)cc1",
    "name": "4-methylphenol",
    "title": "P-Cresol",
    "difficulty": "medium"
  },
  {
    "category": "aromatics",
    "smiles": "c1ccccc1N",
    "name": "aniline",
    "title": "Aniline",
    "difficulty": "easy"
  },
  {
    "category": "aromatics",
    "smiles": "c1ccccc1C=O",
    "name": "benzaldehyde",
    "title": "Benzaldehyde",
    "difficulty": "medium"
  },
  {
    "category": "aromatics",
    "smiles": "c1ccccc1",
    "name": "benzene",
    "title": "Benzene",
    "difficulty": "easy"
  },
  {
    "category": "aromatics",
    "smiles": "c1ccccc1C(=O)O",
    "name": "benzoic acid",
    "title": "Benzoic Acid",
    "difficulty": "medium"
  },
  {
    "category": "aromatics",
    "smiles": "c1ccccc1Br",
    "name": "bromobenzene",
    "title": "Bromobenzene",
    "difficulty": "easy"
  },
  {
    "category": "aromatics",
    "smiles": "c1ccccc1Cl",
    "name": "chlorobenzene",
    "title": "Chlorobenzene",
    "difficulty": "easy"
  },
  {
    "category": "aromatics",
    "smiles": "c1ccccc1CC",
    "name": "ethylbenzene",
    "title": "Ethylbenzene",
    "difficulty": "medium"
  },
  {
    "category": "aromatics",
    "smiles": "c1ccc2ccccc2c1",
    "name": "naphthalene",
    "title": "Naphthalene",
    "difficulty": "medium"
  },
  {
    "category": "aromatics",
    "smiles": "c1ccccc1[N+](=O)[O-]",
    "name": "nitrobenzene",
    "title": "Nitrobenzene",
    "difficulty": "easy"
  },
  {
    "category": "aromatics",
    "smiles": "c1ccccc1O",
    "name": "phenol",
    "title": "Phenol",
    "difficulty": "easy"
  },
  {
    "category": "aromatics",
    "smiles": "c1ccccc1CCC",
    "name": "propylbenzene",
    "title": "Propylbenzene",
    "difficulty": "medium"
  },
  {
    "category": "aromatics",
    "smiles": "C=Cc1ccccc1",
    "name": "styrene",
    "title": "Styrene",
    "difficulty": "medium"
  },
  {
    "category": "aromatics",
    "smiles": "c1ccccc1C",
    "name": "toluene",
    "title": "Toluene",
    "difficulty": "easy"
  },
  {
    "category": "carbonyls",
    "smiles": "CC1CCCCC1=O",
    "name": "2-methylcyclohexan-1-one",
    "title": "2-Methylcyclohexanone",
    "difficulty": "hard"
  },
  {
    "category": "carbonyls",
    "smiles": "CC(C)C=O",
    "name": "2-methylpropanal",
    "title": "Isobutyraldehyde",
    "difficulty": "easy"
  },
  {
    "category": "carbonyls",
    "smiles": "CCC(C)C(=O)C(C)C",
    "name": "2,4-dimethylhexan-3-one",
    "title": "2,4-Dimethyl-3-Hexanone",
    "difficulty": "hard"
  },
  {
    "category": "carbonyls",
    "smiles": "CC(C)CC(C)C=O",
    "name": "2,4-dimethylpentanal",
    "title": "2,4-Dimethylpentanal",
    "difficulty": "hard"
  },
  {
    "category": "carbonyls",
    "smiles": "CC(C)CC(=O)C(C)C",
    "name": "2,5-dimethylhexan-3-one",
    "title": "3-hexanone, 2,5-dimethyl-(8ci)",
    "difficulty": "hard"
  },
  {
    "category": "carbonyls",
    "smiles": "CC(C)C(C)=O",
    "name": "3-methylbutan-2-one",
    "title": "3-Methyl-2-butanone",
    "difficulty": "medium"
  },
  {
    "category": "carbonyls",
    "smiles": "CC(C)CC=O",
    "name": "3-methylbutanal",
    "title": "3-Methylbutanal",
    "difficulty": "easy"
  },
  {
    "category": "carbonyls",
    "smiles": "O=C1CC(C)CCC1",
    "name": "3-methylcyclohexan-1-one",
    "title": "3-Methylcyclohexanone",
    "difficulty": "hard"
  },
  {
    "category": "carbonyls",
    "smiles": "CC(C)CC(=O)CC",
    "name": "5-methylhexan-3-one",
    "title": "5-Methylhexan-3-one",
    "difficulty": "medium"
  },
  {
    "category": "carbonyls",
    "smiles": "CC(=O)CC",
    "name": "butan-2-one",
    "title": "Methyl Ethyl Ketone",
    "difficulty": "easy"
  },
  {
    "category": "carbonyls",
    "smiles": "CCCC=O",
    "name": "butanal",
    "title": "Butanal",
    "difficulty": "easy"
  },
  {
    "category": "carbonyls",
    "smiles": "O=C1CCCCC1",
    "name": "cyclohexanone",
    "title": "Cyclohexanone",
    "difficulty": "easy"
  },
  {
    "category": "carbonyls",
    "smiles": "O=C1CCCC1",
    "name": "cyclopentanone",
    "title": "Cyclopentanone",
    "difficulty": "easy"
  },
  {
    "category": "carbonyls",
    "smiles": "CC(=O)CCCCC",
    "name": "heptan-2-one",
    "title": "2-Heptanone",
    "difficulty": "easy"
  },
  {
    "category": "carbonyls",
    "smiles": "CCC(=O)CCCC",
    "name": "heptan-3-one",
    "title": "3-Heptanone",
    "difficulty": "easy"
  },
  {
    "category": "carbonyls",
    "smiles": "CCCC(=O)CCC",
    "name": "heptan-4-one",
    "title": "4-Heptanone",
    "difficulty": "easy"
  },
  {
    "category": "carbonyls",
    "smiles": "CCCCCCC=O",
    "name": "heptanal",
    "title": "Heptanal",
    "difficulty": "easy"
  },
  {
    "category": "carbonyls",
    "smiles": "CC(=O)CCCC",
    "name": "hexan-2-one",
    "title": "2-Hexanone",
    "difficulty": "easy"
  },
  {
    "category": "carbonyls",
    "smiles": "CCC(=O)CCC",
    "name": "hexan-3-one",
    "title": "3-Hexanone",
    "difficulty": "easy"
  },
  {
    "category": "carbonyls",
    "smiles": "CCCCCC=O",
    "name": "hexanal",
    "title": "Hexanal",
    "difficulty": "easy"
  },
  {
    "category": "carbonyls",
    "smiles": "CC(=O)CCC",
    "name": "pentan-2-one",
    "title": "2-Pentanone",
    "difficulty": "easy"
  },
  {
    "category": "carbonyls",
    "smiles": "CCC(=O)CC",
    "name": "pentan-3-one",
    "title": "Ethyl ketone",
    "difficulty": "easy"
  },
  {
    "category": "carbonyls",
    "smiles": "CCCCC=O",
    "name": "pentanal",
    "title": "Pentanal",
    "difficulty": "easy"
  },
  {
    "category": "carbonyls",
    "smiles": "CC(=O)CC(C)=O",
    "name": "pentane-2,4-dione",
    "title": "Acetylacetone",
    "difficulty": "medium"
  },
  {
    "category": "carbonyls",
    "smiles": "CCC=O",
    "name": "propanal",
    "title": "Propanal",
    "difficulty": "easy"
  },
  {
    "category": "carbonyls",
    "smiles": "O=CCC=O",
    "name": "propanedial",
    "title": "Malonaldehyde",
    "difficulty": "easy"
  },
  {
    "category": "halides",
    "smiles": "BrCC(C)C",
    "name": "1-bromo-2-methylpropane",
    "title": "1-Bromo-2-methylpropane",
    "difficulty": "medium"
  },
  {
    "category": "halides",
    "smiles": "ClCCCCBr",
    "name": "1-bromo-4-chlorobutane",
    "title": "1-Bromo-4-chlorobutane",
    "difficulty": "easy"
  },
  {
    "category": "halides",
    "smiles": "C(Br)CCC",
    "name": "1-bromobutane",
    "title": "Butyl bromide",
    "difficulty": "easy"
  },
  {
    "category": "halides",
    "smiles": "C(Br)CCCCC",
    "name": "1-bromohexane",
    "title": "1-Bromohexane",
    "difficulty": "easy"
  },
  {
    "category": "halides",
    "smiles": "C(Br)CCCC",
    "name": "1-bromopentane",
    "title": "1-Bromopentane",
    "difficulty": "easy"
  },
  {
    "category": "halides",
    "smiles": "C(Br)CC",
    "name": "1-bromopropane",
    "title": "1-Bromopropane",
    "difficulty": "easy"
  },
  {
    "category": "halides",
    "smiles": "C(Cl)CCC",
    "name": "1-chlorobutane",
    "title": "Butyl Chloride",
    "difficulty": "easy"
  },
  {
    "category": "halides",
    "smiles": "C(Cl)CCCCC",
    "name": "1-chlorohexane",
    "title": "1-Chlorohexane",
    "difficulty": "easy"
  },
  {
    "category": "halides",
    "smiles": "C(Cl)CCCC",
    "name": "1-chloropentane",
    "title": "1-Chloropentane",
    "difficulty": "easy"
  },
  {
    "category": "halides",
    "smiles": "C(Cl)CC",
    "name": "1-chloropropane",
    "title": "1-Chloropropane",
    "difficulty": "easy"
  },
  {
    "category": "halides",
    "smiles": "C(F)CCC",
    "name": "1-fluorobutane",
    "title": "1-Fluorobutane",
    "difficulty": "easy"
  },
  {
    "category": "halides",
    "smiles": "C(F)CCCCC",
    "name": "1-fluorohexane",
    "title": "1-Fluorohexane",
    "difficulty": "easy"
  },
  {
    "category": "halides",
    "smiles": "C(F)CCCC",
    "name": "1-fluoropentane",
    "title": "1-Fluoropentane",
    "difficulty": "easy"
  },
  {
    "category": "halides",
    "smiles": "C(F)CC",
    "name": "1-fluoropropane",
    "title": "Propane, 1-fluoro-",
    "difficulty": "easy"
  },
  {
    "category": "halides",
    "smiles": "C(I)CCC",
    "name": "1-iodobutane",
    "title": "Butyl iodide",
    "difficulty": "easy"
  },
  {
    "category": "halides",
    "smiles": "C(I)CCCCC",
    "name": "1-iodohexane",
    "title": "1-Iodohexane",
    "difficulty": "easy"
  },
  {
    "category": "halides",
    "smiles": "C(I)CCCC",
    "name": "1-iodopentane",
    "title": "1-Iodopentane",
    "difficulty": "easy"
  },
  {
    "category": "halides",
    "smiles": "C(I)CC",
    "name": "1-iodopropane",
    "title": "1-Iodopropane",
    "difficulty": "easy"
  },
  {
    "category": "halides",
    "smiles": "ClC(Cl)(Cl)C",
    "name": "1,1,1-trichloroethane",
    "title": "1,1,1-Trichloroethane",
    "difficulty": "easy"
  },
  {
    "category": "halides",
    "smiles": "ClCCCl",
    "name": "1,2-dichloroethane",
    "title": "1,2-Dichloroethane",
    "difficulty": "medium"
  },
  {
    "category": "halides",
    "smiles": "ClCC(Cl)C",
    "name": "1,2-dichloropropane",
    "title": "1,2-Dichloropropane",
    "difficulty": "hard"
  },
  {
    "category": "halides",
    "smiles": "CC(Br)C(C)C",
    "name": "2-bromo-3-methylbutane",
    "title": "2-Bromo-3-methylbutane",
    "difficulty": "hard"
  },
  {
    "category": "halides",
    "smiles": "BrC(C)C(C)CC",
    "name": "2-bromo-3-methylpentane",
    "title": "2-Bromo-3-methylpentane",
    "difficulty": "hard"
  },
  {
    "category": "halides",
    "smiles": "CC(Br)CC",
    "name": "2-bromobutane",
    "title": "2-Bromobutane",
    "difficulty": "medium"
  },
  {
    "category": "halides",
    "smiles": "CC(Br)CCCC",
    "name": "2-bromohexane",
    "title": "2-Bromohexane",
    "difficulty": "medium"
  },
  {
    "category": "halides",
    "smiles": "CC(Br)CCC",
    "name": "2-bromopentane",
    "title": "2-Bromopentane",
    "difficulty": "medium"
  },
  {
    "category": "halides",
    "smiles": "CC(Br)C",
    "name": "2-bromopropane",
    "title": "2-Bromopropane",
    "difficulty": "easy"
  },
  {
    "category": "halides",
    "smiles": "CC(C)(Cl)C",
    "name": "2-chloro-2-methylpropane",
    "title": "tert-BUTYL CHLORIDE",
    "difficulty": "easy"
  },
  {
    "category": "halides",
    "smiles": "CC(C)CC(Cl)C",
    "name": "2-chloro-4-methylpentane",
    "title": "Pentane, 2-chloro-4-methyl-",
    "difficulty": "hard"
  },
  {
    "category": "halides",
    "smiles": "CC(Cl)CC",
    "name": "2-chlorobutane",
    "title": "2-Chlorobutane",
    "difficulty": "medium"
  },
  {
    "category": "halides",
    "smiles": "CC(Cl)CCCC",
    "name": "2-chlorohexane",
    "title": "Hexane, 2-chloro-",
    "difficulty": "medium"
  },
  {
    "category": "halides",
    "smiles": "CC(Cl)CCC",
    "name": "2-chloropentane",
    "title": "2-Chloropentane",
    "difficulty": "medium"
  },
  {
    "category": "halides",
    "smiles": "CC(Cl)C",
    "name": "2-chloropropane",
    "title": "2-Chloropropane",
    "difficulty": "easy"
  },
  {
    "category": "halides",
    "smiles": "CC(F)CC",
    "name": "2-fluorobutane",
    "title": "2-Fluorobutane",
    "difficulty": "medium"
  },
  {
    "category": "halides",
    "smiles": "CC(F)CCCC",
    "name": "2-fluorohexane",
    "title": "2-Fluorohexane",
    "difficulty": "medium"
  },
  {
    "category": "halides",
    "smiles": "CC(F)CCC",
    "name": "2-fluoropentane",
    "title": "2-Fluoropentane",
    "difficulty": "medium"
  },
  {
    "category": "halides",
    "smiles": "CC(F)C",
    "name": "2-fluoropropane",
    "title": "2-Fluoropropane",
    "difficulty": "easy"
  },
  {
    "category": "halides",
    "smiles": "CC(I)CC",
    "name": "2-iodobutane",
    "title": "2-Iodobutane",
    "difficulty": "medium"
  },
  {
    "category": "halides",
    "smiles": "CC(I)CCCC",
    "name": "2-iodohexane",
    "title": "2-Iodohexane",
    "difficulty": "medium"
  },
  {
    "category": "halides",
    "smiles": "CC(I)CCC",
    "name": "2-iodopentane",
    "title": "2-Iodopentane",
    "difficulty": "medium"
  },
  {
    "category": "halides",
    "smiles": "CC(I)C",
    "name": "2-iodopropane",
    "title": "Isopropyl iodide",
    "difficulty": "easy"
  },
  {
    "category": "halides",
    "smiles": "CCC(Br)CCC",
    "name": "3-bromohexane",
    "title": "3-Bromohexane",
    "difficulty": "medium"
  },
  {
    "category": "halides",
    "smiles": "CCC(Br)CC",
    "name": "3-bromopentane",
    "title": "3-Bromopentane",
    "difficulty": "easy"
  },
  {
    "category": "halides",
    "smiles": "CC(C)C(Cl)C(C)C",
    "name": "3-chloro-2,4-dimethylpentane",
    "title": "3-Chloro-2,4-dimethylpentane",
    "difficulty": "hard"
  },
  {
    "category": "halides",
    "smiles": "CCC(Cl)CCC",
    "name": "3-chlorohexane",
    "title": "3-Chlorohexane",
    "difficulty": "medium"
  },
  {
    "category": "halides",
    "smiles": "CCC(Cl)CC",
    "name": "3-chloropentane",
    "title": "3-Chloropentane",
    "difficulty": "easy"
  },
  {
    "category": "halides",
    "smiles": "CCC(F)CCC",
    "name": "3-fluorohexane",
    "title": "3-Fluorohexane",
    "difficulty": "medium"
  },
  {
    "category": "halides",
    "smiles": "CCC(F)CC",
    "name": "3-fluoropentane",
    "title": "3-Fluoropentane",
    "difficulty": "easy"
  },
  {
    "category": "halides",
    "smiles": "CCC(I)CCC",
    "name": "3-iodohexane",
    "title": "3-Iodohexane",
    "difficulty": "medium"
  },
  {
    "category": "halides",
    "smiles": "CCC(I)CC",
    "name": "3-iodopentane",
    "title": "3-Iodopentane",
    "difficulty": "easy"
  },
  {
    "category": "unsaturated",
    "smiles": "C/C=C/C=C/C",
    "name": "(2E,4E)-hexa-2,4-diene",
    "title": "trans,trans-2,4-Hexadiene",
    "difficulty": "hard"
  },
  {
    "category": "unsaturated",
    "smiles": "CC/C=C/C(C)C",
    "name": "(E)-2-methylhex-3-ene",
    "title": "(3E)-2-Methyl-3-hexene",
    "difficulty": "hard"
  },
  {
    "category": "unsaturated",
    "smiles": "C/C=C/C",
    "name": "(E)-but-2-ene",
    "title": "trans-2-BUTENE",
    "difficulty": "medium"
  },
  {
    "category": "unsaturated",
    "smiles": "C/C=C/CC",
    "name": "(E)-pent-2-ene",
    "title": "trans-2-Pentene",
    "difficulty": "medium"
  },
  {
    "category": "unsaturated",
    "smiles": "C/C=C\\C",
    "name": "(Z)-but-2-ene",
    "title": "cis-2-BUTENE",
    "difficulty": "medium"
  },
  {
    "category": "unsaturated",
    "smiles": "CC/C=C\\CC",
    "name": "(Z)-hex-3-ene",
    "title": "cis-3-Hexene",
    "difficulty": "medium"
  },
  {
    "category": "unsaturated",
    "smiles": "CC1=CCCCC1",
    "name": "1-methylcyclohexene",
    "title": "1-Methylcyclohexene",
    "difficulty": "easy"
  },
  {
    "category": "unsaturated",
    "smiles": "CC1=CC(C)CCC1",
    "name": "1,3-dimethylcyclohexene",
    "title": "1,3-Dimethyl-1-cyclohexene",
    "difficulty": "hard"
  },
  {
    "category": "unsaturated",
    "smiles": "CC(C)=CC",
    "name": "2-methylbut-2-ene",
    "title": "2-Methyl-2-butene",
    "difficulty": "easy"
  },
  {
    "category": "unsaturated",
    "smiles": "CC(C)=C",
    "name": "2-methylprop-1-ene",
    "title": "Isobutylene",
    "difficulty": "medium"
  },
  {
    "category": "unsaturated",
    "smiles": "CC(C)C=C(C)C",
    "name": "2,4-dimethylpent-2-ene",
    "title": "2,4-Dimethylpent-2-ene",
    "difficulty": "hard"
  },
  {
    "category": "unsaturated",
    "smiles": "CCC(C)C=CC",
    "name": "4-methylhex-2-ene",
    "title": "4-Methylhex-2-ene",
    "difficulty": "hard"
  },
  {
    "category": "unsaturated",
    "smiles": "C=CCC",
    "name": "but-1-ene",
    "title": "1-Butene",
    "difficulty": "easy"
  },
  {
    "category": "unsaturated",
    "smiles": "C#CCC",
    "name": "but-1-yne",
    "title": "1-Butyne",
    "difficulty": "easy"
  },
  {
    "category": "unsaturated",
    "smiles": "CC=CC",
    "name": "but-2-ene",
    "title": "But-2-ene",
    "difficulty": "easy"
  },
  {
    "category": "unsaturated",
    "smiles": "CC#CC",
    "name": "but-2-yne",
    "title": "Dimethylacetylene",
    "difficulty": "easy"
  },
  {
    "category": "unsaturated",
    "smiles": "C=CC=C",
    "name": "buta-1,3-diene",
    "title": "1,3-Butadiene",
    "difficulty": "medium"
  },
  {
    "category": "unsaturated",
    "smiles": "C1=CCCCC1",
    "name": "cyclohexene",
    "title": "Cyclohexene",
    "difficulty": "easy"
  },
  {
    "category": "unsaturated",
    "smiles": "C=CCCCCC",
    "name": "hept-1-ene",
    "title": "1-Heptene",
    "difficulty": "easy"
  },
  {
    "category": "unsaturated",
    "smiles": "C#CCCCCC",
    "name": "hept-1-yne",
    "title": "1-Heptyne",
    "difficulty": "easy"
  },
  {
    "category": "unsaturated",
    "smiles": "CC=CCCCC",
    "name": "hept-2-ene",
    "title": "2-Heptene",
    "difficulty": "easy"
  },
  {
    "category": "unsaturated",
    "smiles": "CC#CCCCC",
    "name": "hept-2-yne",
    "title": "Hept-2-yne",
    "difficulty": "easy"
  },
  {
    "category": "unsaturated",
    "smiles": "CCC=CCCC",
    "name": "hept-3-ene",
    "title": "3-Heptene",
    "difficulty": "easy"
  },
  {
    "category": "unsaturated",
    "smiles": "CCC#CCCC",
    "name": "hept-3-yne",
    "title": "Hept-3-yne",
    "difficulty": "easy"
  },
  {
    "category": "unsaturated",
    "smiles": "C=CCCCC",
    "name": "hex-1-ene",
    "title": "1-Hexene",
    "difficulty": "easy"
  },
  {
    "category": "unsaturated",
    "smiles": "C#CCCCC",
    "name": "hex-1-yne",
    "title": "1-Hexyne",
    "difficulty": "easy"
  },
  {
    "category": "unsaturated",
    "smiles": "CC=CCCC",
    "name": "hex-2-ene",
    "title": "Hex-2-ene",
    "difficulty": "easy"
  },
  {
    "category": "unsaturated",
    "smiles": "CC#CCCC",
    "name": "hex-2-yne",
    "title": "2-Hexyne",
    "difficulty": "easy"
  },
  {
    "category": "unsaturated",
    "smiles": "CCC=CCC",
    "name": "hex-3-ene",
    "title": "3-Hexene",
    "difficulty": "easy"
  },
  {
    "category": "unsaturated",
    "smiles": "CCC#CCC",
    "name": "hex-3-yne",
    "title": "3-Hexyne",
    "difficulty": "easy"
  },
  {
    "category": "unsaturated",
    "smiles": "C=CCCC",
    "name": "pent-1-ene",
    "title": "1-Pentene",
    "difficulty": "easy"
  },
  {
    "category": "unsaturated",
    "smiles": "C#CCCC",
    "name": "pent-1-yne",
    "title": "1-Pentyne",
    "difficulty": "easy"
  },
  {
    "category": "unsaturated",
    "smiles": "CC=CCC",
    "name": "pent-2-ene",
    "title": "Pent-2-ene",
    "difficulty": "easy"
  },
  {
    "category": "unsaturated",
    "smiles": "CC#CCC",
    "name": "pent-2-yne",
    "title": "2-Pentyne",
    "difficulty": "easy"
  },
  {
    "category": "unsaturated",
    "smiles": "CC=CC=C",
    "name": "penta-1,3-diene",
    "title": "Penta-1,3-diene",
    "difficulty": "medium"
  },
  {
    "category": "unsaturated",
    "smiles": "C=CCC=C",
    "name": "penta-1,4-diene",
    "title": "1,4-Pentadiene",
    "difficulty": "medium"
  }
];
